[mgr]
show_hidden    = true
sort_by        = "natural"
sort_dir_first = true
scrolloff      = 5

[preview]
max_width     = 1000
max_height    = 1200
image_delay   = 30
image_filter  = "triangle"
image_quality = 75

[tasks]
image_alloc = 1073741824
